In [1]:
#Write a function so that the columns of the output matrix are powers of the input vector. 
#The order of the powers is determined by the increasing boolean argument. Specifically, when  increasing is False, the i-th
#output column is the input vector raised element-wise to the power  of N - i - 1. 
#HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde. 


In [3]:
import numpy as np

In [4]:
arr=np.array([5,6,7,8])

In [9]:
x=4

In [10]:
np.vander(arr,x)

array([[125,  25,   5,   1],
       [216,  36,   6,   1],
       [343,  49,   7,   1],
       [512,  64,   8,   1]])

In [11]:
np.vander(arr,x,increasing=False)

array([[125,  25,   5,   1],
       [216,  36,   6,   1],
       [343,  49,   7,   1],
       [512,  64,   8,   1]])

In [12]:
np.vander(arr,x,increasing=True)

array([[  1,   5,  25, 125],
       [  1,   6,  36, 216],
       [  1,   7,  49, 343],
       [  1,   8,  64, 512]])

In [13]:
#Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of  the given sequence is defined as follows: 
#The moving average sequence has n-k+1 elements as shown below. 
#The moving averages with k=4 of a ten-value sequence (n=10) is shown below 
#i 1 2 3 4 5 6 7 8 9 10 
#===== == == == == == == == == == == 
#Input 10 20 30 40 50 60 70 80 90 100  
#y1 25 = (10+20+30+40)/4 
#y2 35 = (20+30+40+50)/4 
#y3 45 = (30+40+50+60)/4 
#y4 55 = (40+50+60+70)/4 
#y5 65 = (50+60+70+80)/4 
#y6 75 = (60+70+80+90)/4 
#y7 85 = (70+80+90+100)/4 
#Thus, the moving average sequence has n-k+1=10-4+1=7 values.


In [37]:
def moving_array(a,n):
    test=np.cumsum(a,dtype=int)
    test[n:]=test[n:]-test[:-n]
    return (test[n-1:])/n

In [39]:
arr1=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [40]:
moving_array(arr1,3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])